admin_actualite_manager:
    path:     /admin/actualite/gestion
    defaults: { _controller: App\Controller\Actualite\ActualiteController::managerAdmin }

admin_actualite_ajouter:
    path:     /admin/actualite/ajouter
    defaults: { _controller: App\Controller\Actualite\ActualiteController::ajouterAdmin }

admin_actualite_publier:
    path:     /admin/actualite/publier/{id}
    defaults: { _controller: App\Controller\Actualite\ActualiteController::publierAdmin }
    requirements:
        id: \d+

admin_actualite_poid:
    path:     /admin/actualite/poid/{id}/{poid}
    defaults:
        _controller: App\Controller\Actualite\ActualiteController::poidAdmin
        poid : 1
    requirements:
        id: \d+
        poid: \d+

admin_actualite_modifier:
    path:     /admin/actualite/modifier/{id}
    defaults: { _controller: App\Controller\Actualite\ActualiteController::modifierAdmin }
    requirements:
        id: \d+

admin_actualite_supprimer:
    path:     /admin/actualite/supprimer/{id}
    defaults: { _controller: App\Controller\Actualite\ActualiteController::supprimerAdmin }
    requirements:
        id: \d+

admin_actualite_supprimer_image:
    path:     /admin/actualite/supprimer-image/{id}
    defaults: { _controller: App\Controller\Actualite\ActualiteController::AdminSupprimerImage }
    requirements:
        id: \d+

client_actualite_manager:
    path:     /actualites
    defaults: { _controller: App\Controller\Actualite\ActualiteController::managerClient }

client_actualite_view:
    path:     /actualite/{slug}/{id}
    defaults: { _controller: App\Controller\Actualite\ActualiteController::viewClient }
    requirements:
        slug: ([a-z-0-9]*)
        id: \d+

#Catégorie
admin_actualitecategorie_manager:
    path:     /admin/actualite-categorie/manager
    defaults: { _controller: App\Controller\Actualite\CategorieController::managerAdmin }

admin_actualitecategorie_ajouter:
    path:     /admin/actualite-categorie/ajouter
    defaults: { _controller: App\Controller\Actualite\CategorieController::ajouterAdmin }

admin_actualitecategorie_modifier:
    path:     /admin/actualite-categorie/modifier/{id}
    defaults: { _controller: App\Controller\Actualite\CategorieController::modifierAdmin }
    requirements:
        id: \d+

admin_actualitecategorie_supprimer:
    path:     /admin/actualite-categorie/supprimer/{id}
    defaults: { _controller: App\Controller\Actualite\CategorieController::supprimerAdmin }
    requirements:
        id: \d+


